[Service]
#ExecStart=%h/.local/bin/kiosk-script cava
########ExecStart=%h/.local/bin/kiosk-script vlc 'file:///home/martin/Videos/koyaanisqatsi.m3u'
#ExecStart=%h/.local/bin/kiosk-script vlc 'file:///home/martin/Videos/matrix.m3u'
ExecStart=%h/.local/bin/kiosk-script vlc 'file:///home/martin/Videos/baraka.m3u'
#ExecStart=%h/.local/bin/kiosk-script vlc 'file:///home/martin/Videos/dvdlogo.webm'
#ExecStart=%h/.local/bin/kiosk-script vlc 'file:///home/martin/Videos/maze.mp4'
#ExecStart=%h/.local/bin/kiosk-script vlc 'v4l2:///dev/video0'
#ExecStart=%h/.local/bin/kiosk-script chromium 'https://mschmitt.github.io/studioclock/?labels=none&theme=brighter&update_interval_ms=10'
#ExecStart=%h/.local/bin/kiosk-script chromium 'https://vdo.ninja/?push=ZQFP7nJ&vd=FaceTime_HD_Camera&ad=0&autostart&webcam&nomirror&fullscreen&autohide'
