[Service]
#ExecStart=%h/.local/bin/kiosk-script cava
#ExecStart=%h/.local/bin/kiosk-script vlc 'file:///home/martin/Videos/koyaanisqatsi.m3u'
ExecStart=%h/.local/bin/kiosk-script vlc 'file:///home/martin/Videos/dvdlogo.webm'
#ExecStart=%h/.local/bin/kiosk-script chromium 'https://mschmitt.github.io/studioclock/?labels=none&theme=brighter&update_interval_ms=10'
